baseurl = "https://roarrraor.github.io/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "RoarrraoR"
    subtitle = "Writing is resistance"
    keywords = ""
    copyright = "©2020 made  with ❤️ by RoarrraoR"
    menuMore = "Show more"
    writtenBy = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"
    lastModDisplay = "Modified:"

    [languages.en.params.logo]
      logoText = "RoarrraoR"
      logoHomeLink = "/"
    # or
    
   path = "/img/fav.gif"
   alt = "RoarrraoR Website"

[languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        #name = "Showcase"
        #url = "/showcase"
	
      [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"
        url = "/home"
